### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [snytkine/LampCMS#126]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by jebradwell-zz** [comment]
Which repository are you referring to? I can create a SECRUITY.md for the
repository with the security issue.

Thank you for reaching out. I hope to hear from you soon.

~Until you spread your wings, You will have no idea how far you can fly!

**Comment by zidingz** [comment]
`snytkine/LampCMS 😊

**Comment by jebradwell-zz** [comment]
Sorry I'm not sure how this message got directed to me. I am not the owner
of this repository. It looks like Dmitri snytkine is. He has a twitter
account that you might be able to get in touch with there. Hope this helps.

Warm regards

**Comment by zidingz** [comment]
That's strange, we have no idea either! Thanks for the advice @jebradwell, good day to you.
